### PR TITLE
Update rsync.js with Windows support

### PR DESCRIPTION
**Pull request by pumuckly**
Add a new function: escapeDirectorySeparator() which used in escapeFileArg() to set directory separator correctly under Windows.
If you use th cygwin's rsync with OpenSSH for Windows (http://www.mls-software.com/opensshd.html) they are using standard linux directory separator and this update can handle directories under Window.
To use rsync under Windows, you need to symlink your directories well (with standard Windows mklink command line tool).

### CODE REVIEW

**Comment by mattijs** [comment]
Thanks for opening a PR.

It would be great if `escapeDirectorySeparator` would be folded into `escapeFileArg` with the appropriate documentation. I think that would be a lot cleaner.

It also needs a few unit tests to show the different patterns that would be matched by this addition.

**Comment by pumuckly** [comment]
Thank you. I done with your requests. Please check the changes.

**Comment by mattijs** [comment]
Thank you for the update. I merged the changes in master and published [v0.6.1](https://www.npmjs.com/package/rsync) to NPM. cheers.

**Comment by born2net** [comment]
please update the docs
TX!

**Comment by mattijs** [comment]
@born2net What docs are out of date in your opinion? This change is mostly under the hood and does not require and specific documentation.

Feel free to open a PR with the docs changes and I'll review them.

**Comment by born2net** [comment]
ha ok, I figured maybe show that in Windows you can now use:
```c:\\path\\path ```
if I understand the fix correctly

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by mattijs** [comment]
Sure, that would be great to add to the README, I just don't have any knowledge about running this on windows. There would have to be a little bit more information than a single sentence.

For example, I don't know if there is a difference between running this on Windows straight up or through Cygwin. This would probably require a different way of escaping. This is probably not a problem because rsync needs to run under Cygwin on Windows (I assume).

**Comment by born2net** [comment]
I understand, let's see maybe the @pumuckly knows

**Pull request merged**
