### PR TITLE
Options and flags for setting file permissions

### PR DESCRIPTION
**Pull request by mattijs**
Added more shorthands to work with file permissions of the transfered files:

  - **chmod(value)**: `--chmod=VALUE` (accumulative)
  - **hardLinks()**: `-H`
  - **perms()**: `-p`
  - **executability()**: `-E`
  - **owner()**: `-o`
  - **group()**: `-g`
  - **acls()**: `-A`
  - **xattrs()**: `-X`
  - **devices()**: `--devices`
  - **specials**: `--specials`
  - **times()**: `-t`

### CODE REVIEW

**Comment by born2net** [comment]
that's awesome, can we also add to the readme all the different option flags?
great job!!!

**Comment by mattijs** [comment]
All the available options are already in the README, look under [option shorthands](https://github.com/mattijs/node-rsync#option-shorthands). All rsync options can be set using the `set` method so this list is not limiting you from using any rsync option (except maybe the accumulative ones).

If you want to know more on the rsync options I suggest you look them up in the rsync man pages, or use this [online version](https://linux.die.net/man/1/rsync).

**Comment by born2net** [comment]
great tx!

**Comment by born2net** [comment]
Checked the readme but I don't see the ones that you added today, like chmod()

**Comment by mattijs** [comment]
@born2net the changes were not merged into the master branch yet. Have another look 😄

**Comment by born2net** [comment]
tx!

**Pull request merged**
